result.pass_optional_args:0 and  result.num_optional_args:2
terminate called after throwing an instance of 'std::runtime_error'
  what():  some optional args are not passed: -ll:cpus  -ll:gpus  
